version: '3'
services: 
  comanda-api: 
    image: comanda_virtual/api
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - elk
    links: 
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=comanda_virtual
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    networks:
      - elk
networks:
  elk: